"""
MUSA - Error Correction Coding Module (Person 2)

Your job: Add Reed-Solomon error correction codes to encoded data.

This makes QR codes scannable even if damaged!

Example:
    Mustapha gives: [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]
    You add: [1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1] (error correction codes)
    
Your functions will be called by Nadir's matrix module.
Reference implementations are in: reed_solomon.py (read-only)
"""

import numpy as np


def add_ecc(data: list, ecc_level: str = "M") -> list:
    """
    Add Reed-Solomon error correction codes to encoded data.
    
    Args:
        data: Encoded bits from Mustapha (list of 0s and 1s)
        ecc_level: Error correction level
                   "L" = 7% recovery   (least)
                   "M" = 15% recovery  (medium - default)
                   "Q" = 25% recovery  (quartile)
                   "H" = 30% recovery  (high)
    
    Returns:
        Extended list with data + ECC codes
    
    Example:
        >>> data = [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]
        >>> ecc_data = add_ecc(data, "M")
        >>> len(ecc_data)
        30  # Original 18 + 12 ECC codes
    
    Step-by-step:
    1. Import reedsolo library (pip install reedsolo)
    2. Determine ECC code count based on level and data length
    3. Create Reed-Solomon encoder with appropriate nsym (number of ECC symbols)
    4. Encode the data to get ECC codes
    5. Return data + ECC codes combined
    """
    # TODO: Implement ECC addition
    raise NotImplementedError("add_ecc() not yet implemented")


def get_ecc_codes(data: np.ndarray, nsym: int) -> np.ndarray:
    """
    Calculate Reed-Solomon error correction codes.
    
    Args:
        data: Input data as numpy array
        nsym: Number of ECC symbols to generate
    
    Returns:
        ECC codes as numpy array
    
    Hint: Use reedsolo.RSCodec(nsym).encode(data)
    """
    # TODO: Implement ECC code generation
    raise NotImplementedError("get_ecc_codes() not yet implemented")


def validate_ecc(data: list, ecc_codes: list) -> bool:
    """
    Verify that ECC codes are correct (optional - for testing).
    
    Args:
        data: Original data
        ecc_codes: ECC codes generated by add_ecc()
    
    Returns:
        True if ECC codes are valid, False otherwise
    """
    # TODO: Implement ECC validation
    raise NotImplementedError("validate_ecc() not yet implemented")


# ============================================================================
# TESTING YOUR WORK
# ============================================================================
#
# Run tests:
#   pytest tests/test_02_ecc.py -v
#
# Your tests will check:
#   ✓ add_ecc() accepts data from Mustapha
#   ✓ ECC codes are correct length for each level
#   ✓ Adding ECC increases total data length
#   ✓ Different levels produce different ECC codes
#   ✓ Multiple texts with ECC work correctly
#
# REFERENCE FILES (READ-ONLY):
#   - reed_solomon.py: Working implementation
#
# DEPENDENCY:
#   Requires MUSTAPHA's encoding working (test_01_encoding.py passing)
#
# When you're done:
#   - All 11 tests pass
#   - Notify NADIR (Person 3) that ECC is ready
#
# ============================================================================
